language: python
python: 2.7
sudo: required
services:
- docker
matrix:
  fast_finish: true
before_script:
- "./linter.sh"
script:
- "./build.sh"
after_success:
- "./repo_build.sh"
env:
  global:
    secure: f1HE9OfzNIoz5BQtbNDAH24PxYj+3QQQIaSWbCtT6fFm+q9RhFL3J4OdJd7OD6404whpBYN0viYs6oC1tA0FRmEG7UgmSLYm9TEgB3prI1nF8It4ASGnbO4sxkulItDpGHBSMpzlsfr/qyx2HYs9EJOa1HcKlG9VMKJY4/LMzeXHgf/Mh4nDoDSw4ypDMCOA3e7YcpRzjSIXIvO2ItVXD9EkYqYbasskS0VFqMQ9I0eC2wsv+5pDZJql0+hFskqiA01veo2/eoJ8Np4USmeuKJ6P+99FQmtM0E99DCx4bEfbVUl42UsIy98F9Acqhb/T7ffdjpmMfVsuvFJGRW5+K+zMJ+arIdu6E6dZawBybKMVtNNXUe04ne/X8C/kpj4MY2YXYeQ8D/KcofOvhQEZPjx4zTiCkSbNjXq0ZX5D9WC2hsqKrxuLdx/PWBT0hpLcgZvoG0MnxabUkOReegsgTxnsLgDggdsK6BILOwQ04QZuzr8HL043+LtA3GJFv3PSc5/Asq/XFS3JK8PkvT15RMNnL7xlBfT+ohIWD1PwR2me5kEss32+cdKQmAfMwlVR26Eon5DDKvnPYEYuCQIdK/kynWTyh2D3LfhREs4tTSaHJlFV3CrEsl9j4z/gTELwQYv2tHue87IeG3Gx3mdfWoCAf1a6EGpQF8EmSjEKV/U=
